set(_CATKIN_CURRENT_PACKAGE "seed_r7_ros_controller")
set(seed_r7_ros_controller_VERSION "0.3.0")
set(seed_r7_ros_controller_MAINTAINER "hi.kondo <hi.kondo@thk.co.jp>")
set(seed_r7_ros_controller_PACKAGE_FORMAT "2")
set(seed_r7_ros_controller_BUILD_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs" "control_msgs" "trajectory_msgs" "nav_msgs" "move_base_msgs" "message_generation" "tf" "realtime_tools" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "joint_limits_interface" "joint_trajectory_controller" "joint_state_controller" "angles" "urdf" "seed_r7_description" "pluginlib" "rostest" "seed_smartactuator_sdk")
set(seed_r7_ros_controller_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs" "control_msgs" "trajectory_msgs" "nav_msgs" "move_base_msgs" "message_generation" "tf" "realtime_tools" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "joint_limits_interface" "joint_trajectory_controller" "joint_state_controller" "angles" "urdf" "seed_r7_description" "pluginlib" "rostest" "seed_smartactuator_sdk")
set(seed_r7_ros_controller_BUILDTOOL_DEPENDS "catkin")
set(seed_r7_ros_controller_BUILDTOOL_EXPORT_DEPENDS )
set(seed_r7_ros_controller_EXEC_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs" "control_msgs" "trajectory_msgs" "nav_msgs" "move_base_msgs" "message_generation" "tf" "realtime_tools" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "joint_limits_interface" "joint_trajectory_controller" "joint_state_controller" "angles" "urdf" "seed_r7_description" "pluginlib" "rostest" "seed_smartactuator_sdk")
set(seed_r7_ros_controller_RUN_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "sensor_msgs" "control_msgs" "trajectory_msgs" "nav_msgs" "move_base_msgs" "message_generation" "tf" "realtime_tools" "control_toolbox" "controller_manager" "hardware_interface" "transmission_interface" "joint_limits_interface" "joint_trajectory_controller" "joint_state_controller" "angles" "urdf" "seed_r7_description" "pluginlib" "rostest" "seed_smartactuator_sdk")
set(seed_r7_ros_controller_TEST_DEPENDS )
set(seed_r7_ros_controller_DOC_DEPENDS )
set(seed_r7_ros_controller_URL_WEBSITE "http://ros.org/wiki/")
set(seed_r7_ros_controller_URL_BUGTRACKER "https://github.com/seed-solutions/noid-ros-pkg/issues")
set(seed_r7_ros_controller_URL_REPOSITORY "https://github.com/noid_moveit_config")
set(seed_r7_ros_controller_DEPRECATED "")