# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: upper_body
  joint_model_group_pose: reset-pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ankle_joint
    - knee_joint
    - waist_y_joint
    - waist_p_joint
    - waist_r_joint
    - l_shoulder_p_joint
    - l_shoulder_r_joint
    - l_shoulder_y_joint
    - l_elbow_joint
    - l_wrist_y_joint
    - l_wrist_p_joint
    - l_wrist_r_joint
    - l_thumb_joint
    - neck_y_joint
    - neck_p_joint
    - neck_r_joint
    - r_shoulder_p_joint
    - r_shoulder_r_joint
    - r_shoulder_y_joint
    - r_elbow_joint
    - r_wrist_y_joint
    - r_wrist_p_joint
    - r_wrist_r_joint
    - r_thumb_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: rarm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r_shoulder_p_joint
      - r_shoulder_r_joint
      - r_shoulder_y_joint
      - r_elbow_joint
      - r_wrist_y_joint
      - r_wrist_p_joint
      - r_wrist_r_joint
  - name: larm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l_shoulder_p_joint
      - l_shoulder_r_joint
      - l_shoulder_y_joint
      - l_elbow_joint
      - l_wrist_y_joint
      - l_wrist_p_joint
      - l_wrist_r_joint
  - name: waist_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - waist_y_joint
      - waist_p_joint
      - waist_r_joint
  - name: lifter_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ankle_joint
      - knee_joint
  - name: head_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - neck_y_joint
      - neck_p_joint
      - neck_r_joint