set(_CATKIN_CURRENT_PACKAGE "seed_r7_robot_interface")
set(seed_r7_robot_interface_VERSION "0.3.0")
set(seed_r7_robot_interface_MAINTAINER "hi.kondo <hi.kondo@thk.co.jp>")
set(seed_r7_robot_interface_PACKAGE_FORMAT "2")
set(seed_r7_robot_interface_BUILD_DEPENDS "roscpp" "seed_r7_ros_controller")
set(seed_r7_robot_interface_BUILD_EXPORT_DEPENDS "roscpp" "seed_r7_ros_controller")
set(seed_r7_robot_interface_BUILDTOOL_DEPENDS "catkin")
set(seed_r7_robot_interface_BUILDTOOL_EXPORT_DEPENDS )
set(seed_r7_robot_interface_EXEC_DEPENDS "roscpp" "seed_r7_ros_controller")
set(seed_r7_robot_interface_RUN_DEPENDS "roscpp" "seed_r7_ros_controller")
set(seed_r7_robot_interface_TEST_DEPENDS )
set(seed_r7_robot_interface_DOC_DEPENDS )
set(seed_r7_robot_interface_URL_WEBSITE "")
set(seed_r7_robot_interface_URL_BUGTRACKER "")
set(seed_r7_robot_interface_URL_REPOSITORY "")
set(seed_r7_robot_interface_DEPRECATED "")