set(_CATKIN_CURRENT_PACKAGE "seed_r7_description")
set(seed_r7_description_VERSION "0.3.0")
set(seed_r7_description_MAINTAINER "hi.kondo <hi.kondo@thk.co.jp>")
set(seed_r7_description_PACKAGE_FORMAT "2")
set(seed_r7_description_BUILD_DEPENDS "xacro")
set(seed_r7_description_BUILD_EXPORT_DEPENDS )
set(seed_r7_description_BUILDTOOL_DEPENDS "catkin")
set(seed_r7_description_BUILDTOOL_EXPORT_DEPENDS )
set(seed_r7_description_EXEC_DEPENDS "xacro")
set(seed_r7_description_RUN_DEPENDS "xacro")
set(seed_r7_description_TEST_DEPENDS )
set(seed_r7_description_DOC_DEPENDS )
set(seed_r7_description_URL_WEBSITE "")
set(seed_r7_description_URL_BUGTRACKER "")
set(seed_r7_description_URL_REPOSITORY "")
set(seed_r7_description_DEPRECATED "")